//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.18444
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class RunThreadableJob: ThreadedJob
{
	private ThreadableI job;

	public RunThreadableJob (ThreadableI job){
		this.job = job;
	}

	/*
	 * Executes the jobs preCalc command.
	 * preCalc cannot use Unity API.
	 */
	protected override void ThreadFunction()
	{
		job.preCalc ();
	}

	/*
	 * Executes the jobs afterCalc command with Unity API.
	 */
	protected override void OnFinished()
	{
		job.afterCalc ();
	}
}

